# Generated by Django 3.2.8 on 2021-11-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300, verbose_name='Title')),
                ('blog_date', models.DateField(verbose_name='Date and Time')),
                ('blog_read_time', models.IntegerField(verbose_name='Read Time')),
                ('blog_tag', models.CharField(default='Python', max_length=200, verbose_name='Tagline')),
                ('blog_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.author')),
            ],
        ),
    ]
