# Generated by Django 3.2.8 on 2021-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='blog_content',
            field=models.TextField(default=0, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
