# Generated by Django 3.2.8 on 2021-11-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_postlist_blog_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostList',
            new_name='Post',
        ),
    ]
